# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-oCi4IgCnbmAURHQY96fnh6V7V9biLa

Start Implmentation by loading the dataset
"""

import pandas as pd

url = "https://raw.githubusercontent.com/propublica/compas-analysis/master/compas-scores-two-years.csv"
df = pd.read_csv(url)
df.head()

"""The COMPAS dataset has already been loaded from the URL in the previous cells. Here is a preview of the DataFrame:"""

display(df.head())

import numpy as np

protected = df["race"]

for col in ["age", "priors_count"]:
    mask_black = (protected == "African-American") & (np.random.rand(len(df)) < 0.3)
    mask_white = (protected == "Caucasian") & (np.random.rand(len(df)) < 0.1)

    df.loc[mask_black, col] = np.nan
    df.loc[mask_white, col] = np.nan

import gurobipy as GRB

# Initialize a Gurobi model
model = GRB.Model("my_optimization_model")

# Placeholder definitions for nodes, features, and leaves.
# You will need to replace these with your actual data.
nodes = []
features = []
leaves = []

P = model.addVars(nodes, features, vtype=GRB.GRB.BINARY)
q = model.addVars(nodes)
c = model.addVars(nodes, vtype=GRB.GRB.BINARY)
u = model.addVars(leaves, vtype=GRB.GRB.BINARY)

classification_error = 0.5
fairness_gap = 0.2
lambda_fair = 1.0

objective = classification_error + lambda_fair * fairness_gap
model.setObjective(objective, GRB.GRB.MINIMIZE)

num_trees = 10  # Example value

for t in range(num_trees):
    model.setParam("TimeLimit", 60)

from scipy.stats import mode

tree_predictions = [0, 1, 0, 1, 0] # Example data

final_pred = mode(tree_predictions).mode.item()

# ============================================
# 1. Install Required Libraries
# ============================================

!pip install fairlearn xgboost -q

# ============================================
# 2. Import Libraries
# ============================================

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from fairlearn.metrics import (
    demographic_parity_difference,
    equalized_odds_difference
)

import warnings
warnings.filterwarnings("ignore")

# ============================================
# 3. Load Dataset
# Adult Income Dataset
# ============================================

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = [
    "age", "workclass", "fnlwgt", "education",
    "education_num", "marital_status", "occupation",
    "relationship", "race", "sex", "capital_gain",
    "capital_loss", "hours_per_week", "native_country",
    "income"
]

df = pd.read_csv(url, names=columns, na_values=" ?", skipinitialspace=True)

print("Dataset Shape:", df.shape)
df.head()

# ============================================
# 4. Handle Missing Values
# ============================================

print("\nMissing Values:")
print(df.isnull().sum())

# ============================================
# 5. Encode Categorical Variables
# ============================================

label_encoders = {}

for col in df.columns:
    if df[col].dtype == 'object':
        le = LabelEncoder()

        # fill temporary missing values for encoding
        df[col] = df[col].astype(str)

        df[col] = le.fit_transform(df[col])

        label_encoders[col] = le

# ============================================
# 6. Define Features and Target
# ============================================

X = df.drop("income", axis=1)
y = df["income"]

# Sensitive attribute for fairness analysis
sensitive_feature = df["sex"]

# ============================================
# 7. Train-Test Split
# ============================================

X_train, X_test, y_train, y_test, s_train, s_test = train_test_split(
    X,
    y,
    sensitive_feature,
    test_size=0.2,
    random_state=42
)

print("\nTraining Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

# ============================================
# 8. Apply Mean Imputation
# ============================================

mean_imputer = SimpleImputer(strategy="mean")

X_train_mean = mean_imputer.fit_transform(X_train)
X_test_mean = mean_imputer.transform(X_test)

# ============================================
# 9. Train Decision Tree Model
# ============================================

dt_model = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

dt_model.fit(X_train_mean, y_train)

# ============================================
# 10. Predictions
# ============================================

y_pred_dt = dt_model.predict(X_test_mean)

# ============================================
# 11. Evaluation
# ============================================

accuracy_dt = accuracy_score(y_test, y_pred_dt)

print("\nDecision Tree Accuracy:")
print(accuracy_dt)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))

# ============================================
# 12. Fairness Metrics
# ============================================

dp_diff = demographic_parity_difference(
    y_true=y_test,
    y_pred=y_pred_dt,
    sensitive_features=s_test
)

eo_diff = equalized_odds_difference(
    y_true=y_test,
    y_pred=y_pred_dt,
    sensitive_features=s_test
)

print("\nFairness Metrics")
print("-------------------------")
print("Demographic Parity Difference:", dp_diff)
print("Equalized Odds Difference:", eo_diff)

# ============================================
# 13. Random Forest Implementation
# ============================================

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=8,
    random_state=42
)

rf_model.fit(X_train_mean, y_train)

y_pred_rf = rf_model.predict(X_test_mean)

accuracy_rf = accuracy_score(y_test, y_pred_rf)

print("\nRandom Forest Accuracy:")
print(accuracy_rf)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

# Fairness Metrics

dp_diff_rf = demographic_parity_difference(
    y_true=y_test,
    y_pred=y_pred_rf,
    sensitive_features=s_test
)

eo_diff_rf = equalized_odds_difference(
    y_true=y_test,
    y_pred=y_pred_rf,
    sensitive_features=s_test
)

print("\nRandom Forest Fairness")
print("-------------------------")
print("Demographic Parity Difference:", dp_diff_rf)
print("Equalized Odds Difference:", eo_diff_rf)

# ============================================
# 14. XGBoost Implementation
# ============================================

xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train_mean, y_train)

y_pred_xgb = xgb_model.predict(X_test_mean)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)

print("\nXGBoost Accuracy:")
print(accuracy_xgb)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

# Fairness Metrics

dp_diff_xgb = demographic_parity_difference(
    y_true=y_test,
    y_pred=y_pred_xgb,
    sensitive_features=s_test
)

eo_diff_xgb = equalized_odds_difference(
    y_true=y_test,
    y_pred=y_pred_xgb,
    sensitive_features=s_test
)

print("\nXGBoost Fairness")
print("-------------------------")
print("Demographic Parity Difference:", dp_diff_xgb)
print("Equalized Odds Difference:", eo_diff_xgb)

# ============================================
# 15. Compare Models
# ============================================

results = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_dt,
        accuracy_rf,
        accuracy_xgb
    ],
    "Demographic Parity Diff": [
        dp_diff,
        dp_diff_rf,
        dp_diff_xgb
    ],
    "Equalized Odds Diff": [
        eo_diff,
        eo_diff_rf,
        eo_diff_xgb
    ]
})

print(results)

# ============================================
# 16. Visualization
# ============================================

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.bar(results["Model"], results["Accuracy"])

plt.ylabel("Accuracy")

plt.title("Model Accuracy Comparison")

plt.show()

plt.figure(figsize=(8,5))

plt.bar(results["Model"], results["Equalized Odds Diff"])

plt.ylabel("Equalized Odds Difference")

plt.title("Fairness Comparison")

plt.show()

df.to_csv('compas_dataset.csv', index=False)
print('COMPAS dataset saved to compas_dataset.csv')

# ============================================
# Reloading Adult Income Dataset
# ============================================

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = [
    "age", "workclass", "fnlwgt", "education",
    "education_num", "marital_status", "occupation",
    "relationship", "race", "sex", "capital_gain",
    "capital_loss", "hours_per_week", "native_country",
    "income"
]

df = pd.read_csv(url, names=columns, na_values=" ?", skipinitialspace=True)

# Re-apply label encoding for categorical features
label_encoders = {}
for col in df.columns:
    if df[col].dtype == 'object':
        le = LabelEncoder()
        df[col] = df[col].astype(str)
        df[col] = le.fit_transform(df[col])
        label_encoders[col] = le

print("Adult Income Dataset Reloaded and Preprocessed.")
print("Dataset Shape:", df.shape)
display(df.head())

"""Now that the Adult Income Dataset is reloaded and preprocessed, we can proceed with the fairness analysis again."""

# Define Features and Target
X = df.drop("income", axis=1)
y = df["income"]
sensitive_feature = df["sex"]

# Train-Test Split
X_train, X_test, y_train, y_test, s_train, s_test = train_test_split(
    X,
    y,
    sensitive_feature,
    test_size=0.2,
    random_state=42
)

print("\nTraining Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

# Apply Mean Imputation
mean_imputer = SimpleImputer(strategy="mean")
X_train_mean = mean_imputer.fit_transform(X_train)
X_test_mean = mean_imputer.transform(X_test)

# Train Decision Tree Model
dt_model = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)
dt_model.fit(X_train_mean, y_train)

# Predictions
y_pred_dt = dt_model.predict(X_test_mean)

# Evaluation
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("\nDecision Tree Accuracy:")
print(accuracy_dt)
print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))

# Fairness Metrics
dp_diff = demographic_parity_difference(
    y_true=y_test,
    y_pred=y_pred_dt,
    sensitive_features=s_test
)
eo_diff = equalized_odds_difference(
    y_true=y_test,
    y_pred=y_pred_dt,
    sensitive_features=s_test
)
print("\nFairness Metrics")
print("-------------------------")
print("Demographic Parity Difference:", dp_diff)
print("Equalized Odds Difference:", eo_diff)

# Random Forest Implementation
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=8,
    random_state=42
)
rf_model.fit(X_train_mean, y_train)
y_pred_rf = rf_model.predict(X_test_mean)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("\nRandom Forest Accuracy:")
print(accuracy_rf)
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

# Fairness Metrics
dp_diff_rf = demographic_parity_difference(
    y_true=y_test,
    y_pred=y_pred_rf,
    sensitive_features=s_test
)
eo_diff_rf = equalized_odds_difference(
    y_true=y_test,
    y_pred=y_pred_rf,
    sensitive_features=s_test
)
print("\nRandom Forest Fairness")
print("-------------------------")
print("Demographic Parity Difference:", dp_diff_rf)
print("Equalized Odds Difference:", eo_diff_rf)

# XGBoost Implementation
xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)
xgb_model.fit(X_train_mean, y_train)
y_pred_xgb = xgb_model.predict(X_test_mean)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print("\nXGBoost Accuracy:")
print(accuracy_xgb)
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

# Fairness Metrics
dp_diff_xgb = demographic_parity_difference(
    y_true=y_test,
    y_pred=y_pred_xgb,
    sensitive_features=s_test
)
eo_diff_xgb = equalized_odds_difference(
    y_true=y_test,
    y_pred=y_pred_xgb,
    sensitive_features=s_test
)
print("\nXGBoost Fairness")
print("-------------------------")
print("Demographic Parity Difference:", dp_diff_xgb)
print("Equalized Odds Difference:", eo_diff_xgb)

# Compare Models
results = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_dt,
        accuracy_rf,
        accuracy_xgb
    ],
    "Demographic Parity Diff": [
        dp_diff,
        dp_diff_rf,
        dp_diff_xgb
    ],
    "Equalized Odds Diff": [
        eo_diff,
        eo_diff_rf,
        eo_diff_xgb
    ]
})
print(results)

"""### Accuracy Comparison Plot"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.bar(results["Model"], results["Accuracy"], color=['skyblue', 'lightcoral', 'lightgreen', 'gold'])
plt.xlabel("Model")
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison on Adult Dataset")
plt.ylim(0, 1) # Accuracy is between 0 and 1
plt.grid(axis='y', linestyle='--')
plt.show()

"""### Equalized Odds Difference Comparison Plot"""

plt.figure(figsize=(10, 6))
plt.bar(results["Model"], results["Equalized Odds Diff"], color=['skyblue', 'lightcoral', 'lightgreen', 'gold'])
plt.xlabel("Model")
plt.ylabel("Equalized Odds Difference")
plt.title("Equalized Odds Difference Comparison on Adult Dataset")
plt.ylim(0, 0.4) # Adjust y-limit based on typical fairness difference ranges
plt.grid(axis='y', linestyle='--')
plt.show()

"""### Performance vs. Fairness Trade-off Visualization"""

import matplotlib.pyplot as plt

# Create a figure with two subplots
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Plot 1: Accuracy Comparison
axes[0].bar(results["Model"], results["Accuracy"], color=['skyblue', 'lightcoral', 'lightgreen', 'gold'])
axes[0].set_xlabel("Model")
axes[0].set_ylabel("Accuracy")
axes[0].set_title("Model Accuracy Comparison")
axes[0].set_ylim(0, 1) # Accuracy is between 0 and 1
axes[0].grid(axis='y', linestyle='--')

# Plot 2: Equalized Odds Difference Comparison
axes[1].bar(results["Model"], results["Equalized Odds Diff"], color=['skyblue', 'lightcoral', 'lightgreen', 'gold'])
axes[1].set_xlabel("Model")
axes[1].set_ylabel("Equalized Odds Difference")
axes[1].set_title("Fairness Comparison (Equalized Odds Difference)")
axes[1].set_ylim(0, results["Equalized Odds Diff"].max() * 1.1) # Dynamic y-limit
axes[1].grid(axis='y', linestyle='--')

plt.tight_layout() # Adjust layout to prevent overlapping titles/labels
plt.show()

"""## Visualize Accuracy vs. Equalized Odds Trade-off"""

import matplotlib.pyplot as plt
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Random Forest",
        "XGBoost",
        "ANN"
    ],
    "Accuracy": [
        accuracy_dt,
        accuracy_rf,
        accuracy_xgb,
        accuracy_ann
    ],
    "Demographic Parity Diff": [
        dp_diff,
        dp_diff_rf,
        dp_diff_xgb,
        dp_diff_ann
    ],
    "Equalized Odds Diff": [
        eo_diff,
        eo_diff_rf,
        eo_diff_xgb,
        eo_diff_ann
    ]
})

plt.figure(figsize=(10, 7))

# Scatter plot
plt.scatter(results["Equalized Odds Diff"], results["Accuracy"], s=200, alpha=0.7, edgecolors='w', linewidth=0.8)

# Annotate each point with the model name
for i, row in results.iterrows():
    plt.annotate(row["Model"], (row["Equalized Odds Diff"] + 0.005, row["Accuracy"] + 0.005), fontsize=9)

plt.xlabel("Equalized Odds Difference (Lower is Fairer)")
plt.ylabel("Accuracy (Higher is Better)")
plt.title("Accuracy vs. Equalized Odds Trade-off")
plt.grid(True, linestyle='--', alpha=0.6)
plt.xlim(results["Equalized Odds Diff"].min() * 0.9, results["Equalized Odds Diff"].max() * 1.1)
plt.ylim(results["Accuracy"].min() * 0.99, results["Accuracy"].max() * 1.01)

plt.show()